config/routes.rb
Rails.application.routes.draw do

  # Devise Facebook Login & Overwriting Devise's default routes
  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks",
    :sessions => "users/sessions"
  }

  # Redirect after sign in
  authenticated :user do
    root to: 'pages#home', as: :authenticated_root
  end

  # Root page
  root to: redirect('/users/sign_in')

  # Sign out page
  get '/signout', to: 'pages#signout', as: 'user_signout'

  get '/user/:username/followings', to: 'pages#followings', as: 'user_followings'
  get '/user/:username/followers', to: 'pages#followers', as: 'user_followers'
  get '/user/:username/tweets', to: 'pages#tweets', as: 'user_tweets'
  get 'tag/:id/tweets', to: 'pages#tweets_by_tag', as: 'tweets_by_tag'


  put '/update_avatar', to: 'users#update_avatar'
=begin
  PUT is used for updating an existing resource
  POST is used for creating a new resource
  In rails 4, PUT has been changed to PATCH to avoid confusion.
=end
  post '/follow/:id', to: 'users#follow', as: 'follow'
  delete '/unfollow/:id', to: 'users#unfollow', as: 'unfollow'

  get 'search', to: 'pages#search'

  # resources :relationships, only: [:create, :destroy]
  resources :tweets, only: [:create, :destroy]

end

app/views/pages/followers.html.slim
- content_for :profile do
  = render partial: "pages/partials/profile", locals: {user: @user}

- content_for :content do
  div.card
    h4.card-header.text-center Followers
    - if @followers.empty?
      p.medium style="padding-top: 2em; padding-left: 2em; font-style: italic" No followers found.

    / ============================================ Pagination ============================================================
    / = link_to_next_page @tweets, 'Next', remote: true, id: 'next-page-link', hidden: true

    / =========================================== List of Followers =====================================================
    ul.followers.list-group
      - @followers.each do |user|
        = render partial: "pages/partials/user", locals: {user: user}

app/views/pages/followings.html.slim
- content_for :profile do
  = render partial: 'pages/partials/profile', locals: {user: @user}

- content_for :content do
  div.card
    h4.card-header.text-center Followings
    - if @followees.empty?
      p.medium style="padding-top: 2em; padding-left: 2em; font-style: italic" No followings found.

    / ============================================ Pagination ============================================================
    / = link_to_next_page @tweets, 'Next', remote: true, id: 'next-page-link', hidden: true

    / =========================================== List of Followings =========================================================
    ul.followings.list-group
      - @followees.each do |user|
        = render partial: 'pages/partials/users', locals: {user: user}

app/views/pages/home.html.slim
- content_for :profile do
  / = render partial: 'pages/partials/trends'
  = render partial: 'pages/partials/profile',  locals: {user: @user}


- content_for :content do
  / ======================================== Tweet Box and List of Tweets ===============================================
  - if @user == current_user
    h4.card-header.text-center style="border: 1px solid rgba(0, 0, 0, 0.125); border-radius: 0.25rem" Write tweet
    div.new-tweet-form
      = simple_form_for Tweet.new, url: tweets_path, method: :post, remote: true do |f|
        = f.input_field :content, label: false, placeholder: "Write your tweet here!", class: 'tweet form-control', maxlength: Tweet:: MAX_WORD_COUNT
        / maxlength: 140 also works. (Using inbuilt HTML input validation, without linking to the Tweet model.) (Not sure which is a better method.)
        div.tweet-button
          span.word-count 140
          span.characters &nbsp;characters remaining.
          = f.button :submit, "Tweet", class: 'btn btn-primary btn-sm'


  div.card
    h4.card-header.text-center Tweets
    - if @tweets.empty?
      p.medium style="padding-top: 2em; padding-left: 2em; font-style: italic" No tweets found.

    / ============================================ Pagination ============================================================
    / = link_to_next_page @tweets, 'Next', remote: true, id: 'next-page-link', hidden: true

    / =========================================== List of Tweets =========================================================
    ul.tweets.list-group
      - @tweets.each do |tweet|
        = render partial: 'tweets/tweets', locals: {tweet: tweet}

  = will_paginate @tweets, class: "pagination"

app/views/pages/home.js.erb
// Not sure if this is necessary still in Rails 5.2, because it seems to work fine without setting AJAX (but just for backup)

// Append tweets
<% @tweets.each do |tweet| %>
$('.tweets').append("<%= j render partial: 'tweets/tweets', locals: {tweet: tweet} %>");
<% end %>
// console.log("Tweets added");

app/views/pages/search.html.slim
- content_for :content do
  div.card
    h4.card-header.text-center Search Results
    ul.nav.nav-pills.mb-3 id="pills-tab" role="tablist"
      li.nav-item
        a.nav-link.active id="pills-user-tab" data-toggle="pill" href="#pills-user" role="tab" aria-controls="pills-user" aria-selected="true" Users
      li.nav-item
        a.nav-link id="pills-tweet-tab" data-toggle="pill" href="#pills-tweet" role="tab" aria-controls="pills-tweet" aria-selected="false" Tweets
      li.nav-item
        a.nav-link id="pills-tag-tab" data-toggle="pill" href="#pills-tag" role="tab" aria-controls="pills-tag" aria-selected="false" Tags

    div.tab-content id="pills-tabContent"
      div.tab-pane.fade.show.active id="pills-user" role="tabpanel" aria-labelledby="pills-user-tab"
        - if @users.empty?
          = content_tag :em, 'No users found.', class: 'small'
        - else
          div.list-group
            - @users.each do |user|
              = render partial: 'pages/partials/users', locals: {user: user}

      div.tab-pane.fade id="pills-tweet" role="tabpanel" aria-labelledby="pills-tweet-tab"
        - if @tweets.empty?
          = content_tag :em, 'No tweets found.', class: 'small'
        - else
          ul.tweets.list-group
            - @tweets.each do |tweet|
              = render partial: 'tweets/tweets', locals: {tweet: tweet}

      div.tab-pane.fade id="pills-tag" role="tabpanel" aria-labelledby="pills-tag-tab"
        - if @tags.empty?
          = content_tag :em, 'No tags found.', class: 'small'
        - else
          div.card.search-tags
            div.card-body
              - @tags.each do |tag|
                = link_to tag.name, tweets_by_tag_path(tag), class: "trend-link"
                | &nbsp;

app/views/pages/signout.html.slim
.container-wrapper-signout        
  .container-signout
    h2 Thank you for using DragonTweet. We hope to see you again. Goodbye!

app/views/pages/tweets.html.slim
- content_for :profile do
  = render partial: 'pages/partials/profile', locals: {user: @user}

- content_for :content do
  div.card
    h4.card-header.text-center Tweets
    - if @tweets.empty?
      p.medium style="padding-top: 2em; padding-left: 2em; font-style: italic" No tweets found.

    / ============================================ Pagination ============================================================
    / = link_to_next_page @tweets, 'Next', remote: true, id: 'next-page-link', hidden: true

    / =========================================== List of Tweets =========================================================
    ul.tweets.list-group
      - @tweets.each do |tweet|
        = render partial: 'tweets/tweets', locals: {tweet: tweet}
    

app/views/pages/tweets.js.erb
// Not sure if this is necessary still in Rails 5.2, because it seems to work fine without setting AJAX (but just for backup)

// Append tweets
<% @tweets.each do |tweet| %>
$('.tweets').append("<%= j render partial: 'tweets/tweets', locals: {tweet: tweet} %>");
<% end %>
// console.log("Tweets added");

app/views/pages/tweets_by_tag.html.slim
- content_for :profile do
  = render partial: 'pages/partials/profile', locals: {user: @user}

- content_for :content do
  span.small.tweet-info
    em Displaying tweets with tag &nbsp
    em = link_to @tag.name, tweets_by_tag_path(@tag), class: "trend-link"

  ul.tweets.list-group.mt-1
    - @tweets.each do |tweet|
      = render partial: 'tweets/tweets', locals: {tweet: tweet}