config/routes.rb
Rails.application.routes.draw do

  # Devise Facebook Login & Overwriting Devise's default routes
  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks",
    :sessions => "users/sessions"
  }

  # Redirect after sign in
  authenticated :user do
    root to: 'pages#home', as: :authenticated_root
  end

  # Root page
  root to: redirect('/users/sign_in')

  # Sign out page
  get '/signout', to: 'pages#signout', as: 'user_signout'

  get '/user/:username/followings', to: 'pages#followings', as: 'user_followings'
  get '/user/:username/followers', to: 'pages#followers', as: 'user_followers'
  get '/user/:username/tweets', to: 'pages#tweets', as: 'user_tweets'
  get 'tag/:id/tweets', to: 'pages#tweets_by_tag', as: 'tweets_by_tag'


  put '/update_avatar', to: 'users#update_avatar'
=begin
  PUT is used for updating an existing resource
  POST is used for creating a new resource
  In rails 4, PUT has been changed to PATCH to avoid confusion.
=end
  post '/follow/:id', to: 'users#follow', as: 'follow'
  delete '/unfollow/:id', to: 'users#unfollow', as: 'unfollow'

  get 'search', to: 'pages#search'

  # resources :relationships, only: [:create, :destroy]
  resources :tweets, only: [:create, :destroy]

end

app/views/pages/partials/_navigationbar.html.slim
/ ================================================== Navbar ===========================================================
nav class="navbar navbar-expand-lg navbar-light bg-light"
  a class="navbar-brand" href="#" DragonTweet
  button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation"
    span class="navbar-toggler-icon"

  div class="collapse navbar-collapse" id="navbarTogglerDemo02"

    / form class="form-inline my-2 my-lg-0"
    /   input class="search form-control" type="search" placeholder="Search for users, tweets or tags here!"
    /   button class="search btn btn-outline-success my-2 my-sm-0" type="submit" Search

    = form_tag search_path, method: :get, class: "form-inline my-2 my-lg-0" do
      = text_field_tag :search, params[:search], class:'search form-control', placeholder: 'Search for users, tweets or tags here!'
      span class="input-group-btn"
      = submit_tag "Search", name: nil, class: 'search btn btn-outline-success my-2 my-sm-0'


    ul class="navbar-nav ml-auto mt-2 mt-lg-0"
      li class="nav-item"
        = link_to "Home", authenticated_root_path, method: :get, class: "nav-link"

      li class="nav-item"
        = link_to "Settings", edit_user_registration_path, method: :get, class: "nav-link"

      li class="nav-item"
        = link_to "Log Out", destroy_user_session_path, method: :delete, data: {confirm: "Are you sure you want to log out?"}, class:"nav-link"

app/views/pages/partials/_profile.html.slim
div.card
  / Filestack (Rails 5.2 has "Content Security Policy". Go to config/initializers/content_security_policy.rb and comment out all the code there or else Filestack picker won't load!)
  / Note the way to dynamically render background images from database using SLIM below!
  div.card-header.profile style="background-image: url(#{user.avatar})"
    - if user.avatar.present? == false && user == current_user
      div.changeavatar-title
        p Click here to change avatar <br> (Please wait for the image uploader to load as I'm using a free plan)
    - elsif user.avatar.present? == false
      div.changeavatar-title
        - if user == current_user
          p Click here to change avatar <br> (Please wait for the image uploader to load as I'm using a free plan)
    - if user == current_user
      = filestack_picker_element 'Change avatar', 'updateAvatar', class: 'btn filestack-btn', pickerOptions: { accept: 'image/*', uploadInBackground: false }
  div.card-body
    h2.name = user.username
    h4.job-title = user.jobtitle
    div.bio = user.biography
    div.quote = " \"#{ user.quote}\" "
    div.social-accounts
      - if current_user == user
        / Do nothing. So Follow/Unfollow button will not show up.
      - else
        a href="#{user.facebook}"
          img.facebook src="/assets/facebook.png"
        a href="#{user.instagram}"
          img.instagram src="/assets/instagram.png"
        a href="mailto:#{user.email}"
          img.gmail src="/assets/mail.png"
    / ====================================== Follow or Unfollow buttons ===========================================
    - if current_user == user
        / Do nothing. So Follow/Unfollow button will not show up.
    - elsif current_user.followees.exists?(user.id)
        div.unfollow-btn.
          = link_to 'Unfollow', unfollow_path(user), class: 'btn unfollow', method: :delete
    - else
        div.follow-btn
          = link_to 'Follow', follow_path(user), class: 'btn follow bg-primary', method: :post

  div.card-footer
    div.stats
      div.stat.followers
        = link_to user_followers_path(user.username), class: "stat-link"
          span.label Followers
          span.value = user.followers.count
      div.stat.followings
        = link_to user_followings_path(user.username), class: "stat-link"
          span.label Followings
          span.value = user.followees.count
      div.stat.tweets
        = link_to user_tweets_path(user.username), class: "stat-link", id: "tweets-count"
          span.label Tweets
          span.value = user.tweets.count

app/views/pages/partials/_trends.html.slim
div.trending.card
  h4.card-header.text-center Latest trends
  ul.trends.list-group.list-group-flush
    - Tag.top_10.each do |tag|
      = link_to tweets_by_tag_path(tag), class: 'list-group-item list-group-item-action d-flex justify-content-between align-items-center border-0' do
        object = link_to tag.name, tweets_by_tag_path(tag), class: "trend-link"
        span.badge.badge-pill = tag.tweets.count.to_s + ' tweets'

app/views/pages/partials/_users.html.slim
= link_to user_tweets_path(user.username), class: 'list-group-item list-group-item-action d-flex justify-content-between align-items-center border-0'
  / = image_tag user.avatar, size: '30', class: 'rounded-circle'
  / = link_to image_tag(tweet.user.avatar, class: "tweet-avatar"), user_tweets_path(tweet.user.username), class: "tweet-avatar"
  - if user.avatar?
    img src="#{user.avatar}" class="tweet-avatar who-to-follow"
    span.user-username = user.username
  - else
    div class="who-to-follow" style="width: 100px; height: 100px"
    span.user-username = user.username

  - if user == current_user
  - elsif current_user.followees.exists?(user.id)
    object = link_to 'Unfollow', unfollow_path(user), class: 'user-unfollow btn btn-outline-danger btn-sm', method: :delete
  - else
    object = link_to 'Follow', follow_path(user), class: 'user-follow btn btn-outline-primary btn-sm', method: :post

app/views/pages/partials/_who_to_follow.html.slim
= link_to user_tweets_path(user.username), class: 'list-group-item list-group-item-action d-flex justify-content-between align-items-center border-0'

  div.bar
    / = image_tag user.avatar, size: '30', class: 'rounded-circle'
    / = link_to image_tag(tweet.user.avatar, class: "tweet-avatar"), user_tweets_path(tweet.user.username), class: "tweet-avatar"
    img src="#{user.avatar}" class="tweet-avatar"
    = user.username

  - if user == current_user
  - elsif current_user.followees.exists?(user.id)
    object = link_to 'Unfollow', unfollow_path(user), class: 'btn btn-outline-danger btn-sm', method: :delete
  - else
    object = link_to 'Follow', follow_path(user), class: 'btn btn-outline-primary btn-sm', method: :post